{, 
	"net" :  {, 
		"if":		"xenif0", 
		"cloner":	"true", 
		"type":	"inet", 
		"method":	"static", 
		"addr":	"10.100.199.37", 
		"mask":	"24", 
	}, 
	"blk" :  {, 
		"source":	"etfs", 
		"path":	"xvda", 
		"fstype":	"cd9660", 
		"mountpoint":	"/data", 
	}, 
	"blk" :  {, 
		"source":	"etfs", 
		"path":	"xvdb", 
		"fstype":	"cd9660", 
		"mountpoint":	"/etc", 
	}, 
	"blk" :  {, 
		"source":	"dev", 
		"path":	"virtual", 
		"fstype":	"kernfs", 
		"mountpoint":	"/kern", 
	}, 
	"cmdline": "bin/phpi.bin -S 0.0.0.0:80 -t /data/www", 
	"hostname": "php-standalone", 
}, 
